import { AudienceQuery, TeamMember } from './types';

export const TEAM_MEMBERS: TeamMember[] = [
  { id: '1', name: 'Sarah Johnson', email: 'sarah@company.com', role: 'Support Lead' },
  { id: '2', name: 'Mike Chen', email: 'mike@company.com', role: 'Support Agent' },
  { id: '3', name: 'Emma Wilson', email: 'emma@company.com', role: 'Support Agent' },
  { id: '4', name: 'David Park', email: 'david@company.com', role: 'Community Manager' },
  { id: '5', name: 'Lisa Anderson', email: 'lisa@company.com', role: 'Social Media Manager' },
];

export const MOCK_QUERIES: AudienceQuery[] = [
  {
    id: '1',
    content: "My order hasn't arrived yet. It's been 2 weeks. Can you help?",
    sender: 'John Smith',
    senderHandle: '@johnsmith',
    channel: 'twitter',
    receivedAt: new Date(Date.now() - 15 * 60000),
    tags: ['complaint', 'request'],
    priority: 'urgent',
    status: 'new',
    lastUpdate: new Date(Date.now() - 15 * 60000),
  },
  {
    id: '2',
    content: 'How do I reset my password on mobile?',
    sender: 'Alice Chen',
    senderHandle: 'alice.chen',
    channel: 'email',
    receivedAt: new Date(Date.now() - 45 * 60000),
    tags: ['question', 'inquiry'],
    priority: 'high',
    status: 'assigned',
    assignedTo: '2',
    lastUpdate: new Date(Date.now() - 30 * 60000),
  },
  {
    id: '3',
    content: 'Love your new product line! Great job on the design.',
    sender: 'Marcus Thompson',
    senderHandle: 'marcus_t',
    channel: 'instagram',
    receivedAt: new Date(Date.now() - 2 * 60000),
    tags: ['feedback'],
    priority: 'low',
    status: 'new',
    lastUpdate: new Date(Date.now() - 2 * 60000),
  },
  {
    id: '4',
    content: 'I found a bug in your checkout process. Credit card field shows error even with valid input.',
    sender: 'Developer Community',
    senderHandle: 'dev_community',
    channel: 'community',
    receivedAt: new Date(Date.now() - 30 * 60000),
    tags: ['bug', 'complaint'],
    priority: 'high',
    status: 'in-progress',
    assignedTo: '1',
    responseTime: 28,
    lastUpdate: new Date(Date.now() - 5 * 60000),
  },
  {
    id: '5',
    content: 'Can I get a bulk discount for orders over 100 units?',
    sender: 'Enterprise Solutions Inc',
    senderHandle: 'ent_solutions',
    channel: 'email',
    receivedAt: new Date(Date.now() - 90 * 60000),
    tags: ['request', 'inquiry'],
    priority: 'high',
    status: 'assigned',
    assignedTo: '3',
    lastUpdate: new Date(Date.now() - 45 * 60000),
  },
  {
    id: '6',
    content: 'When is the next sale happening?',
    sender: 'Casual Buyer',
    senderHandle: 'casual_buyer',
    channel: 'facebook',
    receivedAt: new Date(Date.now() - 120 * 60000),
    tags: ['question'],
    priority: 'medium',
    status: 'resolved',
    assignedTo: '5',
    responseTime: 45,
    lastUpdate: new Date(Date.now() - 60 * 60000),
  },
  {
    id: '7',
    content: 'The app keeps crashing when I try to upload images.',
    sender: 'Tech Support Thread',
    senderHandle: 'support_thread',
    channel: 'chat',
    receivedAt: new Date(Date.now() - 5 * 60000),
    tags: ['bug', 'complaint'],
    priority: 'urgent',
    status: 'new',
    lastUpdate: new Date(Date.now() - 5 * 60000),
  },
  {
    id: '8',
    content: 'Just wanted to say thank you for the great customer service last week!',
    sender: 'Happy Customer',
    senderHandle: 'happy_customer',
    channel: 'twitter',
    receivedAt: new Date(Date.now() - 180 * 60000),
    tags: ['feedback'],
    priority: 'low',
    status: 'closed',
    responseTime: 120,
    lastUpdate: new Date(Date.now() - 175 * 60000),
  },
];
